# Generated by Django 5.0.3 on 2024-03-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_landmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landmark",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="landmark",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
