# Generated by Django 5.0.3 on 2024-04-29 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CRS", "0002_remove_croprecommendation_landid"),
        ("accounts", "0004_alter_user_profile_pic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Landmark",
        ),
    ]
