# Generated by Django 5.0.3 on 2024-04-29 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CRS", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="croprecommendation",
            name="landId",
        ),
    ]
