# Generated by Django 5.0.3 on 2024-04-29 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("CRS", "0003_delete_croprecommendation"),
        ("accounts", "0006_landmark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CropRecommendation",
            fields=[
                (
                    "cropId",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("N", models.PositiveIntegerField()),
                ("P", models.PositiveIntegerField()),
                ("K", models.PositiveIntegerField()),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("ph", models.FloatField(blank=True, null=True)),
                ("rainfall", models.FloatField(blank=True, null=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("prediction", models.CharField(max_length=255)),
                (
                    "landId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.landmark",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
