# Generated by Django 5.0.3 on 2024-05-10 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CRS", "0004_initial"),
        ("accounts", "0006_landmark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviousCropRequest",
            fields=[
                (
                    "requestId",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("season", models.CharField(max_length=20)),
                ("month", models.PositiveIntegerField()),
                ("crop", models.CharField(max_length=100)),
                ("area", models.FloatField()),
                ("production", models.FloatField(blank=True, null=True)),
                ("yield_per_hectare", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "landId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.landmark",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
